#Helm_Lab
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}   
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}        
    spec:      
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.deployment.port }}

############################################################################################################################################################
#Jenkins_Lab2
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: bakehouse
#   name: bakehouse
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: bakehouse
#   template:
#     metadata:
#       labels:
#         app: bakehouse
#     spec:
#       containers:
#       - image: ahmedibrahimcs/bakehouse:v${BUILD_NUMBER}
#         name: bakehouse
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 80
#         resources: {}
