#Helm_Lab

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}  
  ports:
  - port: {{ .Values.service.port }}      
    targetPort: {{ .Values.deployment.port }}
  selector: 
    app: {{ .Values.deployment.name }}


##################################################################################################################################################################
#Jenkins_Lab2
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: myservice
#   name: myservice
# spec:
#   ports:
#   - name: bakehouseport
#     port: 80
#     protocol: TCP
#     targetPort: 80
#   selector:
#     app: bakehouse
#   type: NodePort
# status:
#   loadBalancer: {}
